-- MySQL Script generated by MySQL Workbench
-- 19 مار, 2018 EET 02:43:46 ص
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema week2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema week2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `week2` DEFAULT CHARACTER SET utf8 ;
USE `week2` ;

-- -----------------------------------------------------
-- Table `week2`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `week2`.`person` (
  `idperson` INT NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(45) NOT NULL UNIQUE,
  `fName` VARCHAR(45) NOT NULL,
  `LName` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idperson`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `week2`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `week2`.`project` (
  `idproject` INT NOT NULL AUTO_INCREMENT,
  `projectName` VARCHAR(45) NOT NULL,
  `person_idperson` INT NOT NULL,
  PRIMARY KEY (`idproject`, `person_idperson`),
  INDEX `fk_project_person_idx` (`person_idperson` ASC),
  CONSTRAINT `fk_project_person`
    FOREIGN KEY (`person_idperson`)
    REFERENCES `week2`.`person` (`idperson`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `week2`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `week2`.`course` (
  `idcourse` INT NOT NULL AUTO_INCREMENT,
  `courseName` VARCHAR(45) NOT NULL,
  `person_idperson` INT NOT NULL,
  PRIMARY KEY (`idcourse`, `person_idperson`),
  INDEX `fk_course_person1_idx` (`person_idperson` ASC),
  CONSTRAINT `fk_course_person1`
    FOREIGN KEY (`person_idperson`)
    REFERENCES `week2`.`person` (`idperson`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `week2`.`language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `week2`.`language` (
  `idlanguage` INT NOT NULL AUTO_INCREMENT,
  `languageName` VARCHAR(45) NOT NULL,
  `person_idperson` INT NOT NULL,
  PRIMARY KEY (`idlanguage`, `person_idperson`),
  INDEX `fk_language_person1_idx` (`person_idperson` ASC),
  CONSTRAINT `fk_language_person1`
    FOREIGN KEY (`person_idperson`)
    REFERENCES `week2`.`person` (`idperson`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `week2`.`hobby`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `week2`.`hobby` (
  `idhobby` INT NOT NULL AUTO_INCREMENT,
  `hobbyName` VARCHAR(45) NOT NULL,
  `person_idperson` INT NOT NULL,
  PRIMARY KEY (`idhobby`, `person_idperson`),
  INDEX `fk_hobby_person1_idx` (`person_idperson` ASC),
  CONSTRAINT `fk_hobby_person1`
    FOREIGN KEY (`person_idperson`)
    REFERENCES `week2`.`person` (`idperson`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `week2`.`site`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `week2`.`site` (
  `idsite` INT NOT NULL AUTO_INCREMENT,
  `siteName` VARCHAR(45) NOT NULL,
  `person_idperson` INT NOT NULL,
  PRIMARY KEY (`idsite`, `person_idperson`),
  INDEX `fk_site_person1_idx` (`person_idperson` ASC),
  CONSTRAINT `fk_site_person1`
    FOREIGN KEY (`person_idperson`)
    REFERENCES `week2`.`person` (`idperson`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `week2`.`app`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `week2`.`app` (
  `idapp` INT NOT NULL AUTO_INCREMENT,
  `appName` VARCHAR(45) NOT NULL,
  `person_idperson` INT NOT NULL,
  PRIMARY KEY (`idapp`, `person_idperson`),
  INDEX `fk_app_person1_idx` (`person_idperson` ASC),
  CONSTRAINT `fk_app_person1`
    FOREIGN KEY (`person_idperson`)
    REFERENCES `week2`.`person` (`idperson`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
